Rogozhkin/#2
Pavel-Rogozhkin/Lubimovka pull request #18
Opened 2022-06-05 16:57 UTC by Pavel-Rogozhkin

Долго что-то мучился с состоянием hover ссылок и с подгоном пикселя.
Понимаю что способ с hover особенно в части разметки громоздкий, но решил его добить...
Если есть идеи как можно удобнее переделать, буду рад исправить)

2022-06-05 20:51 UTC, nlog675 reviewed
Привет)
Заранее извиняюсь, если что отметил не так, не до конца разобрался как делать ревью тут)) я только код посмотрел и некоторые моменты отметил, не знаю, можно ли как то открыть в браузере и посмотреть как все выглядит:)

2022-06-05 20:51 UTC, nlog675 commented on blocks/header/__link/_active/header__link_active.css
> +
а это ничего страшного, что пустой стиль?:)

2022-06-05 20:51 UTC, nlog675 commented on index.html
> +        <li class="header__navi-link"></li><a class="header__link" href="#">
здесь и в дальнейших пунктах списка тег <li>  закрывается по два раза

2022-06-05 20:51 UTC, nlog675 commented on index.html
> +        <li class="header__navi-link"></li><a class="header__link" href="#">
там тег ли, извиняюсь, он сам список сделал в комментарии))

2022-06-06 04:57 UTC, Pavel-Rogozhkin commented on index.html
> +        <li class="header__navi-link"></li><a class="header__link" href="#">
Вечером исправлю.

2022-06-06 04:58 UTC, Pavel-Rogozhkin commented on blocks/header/__link/_active/header__link_active.css
> +
Это на будущее для js

2022-06-08 16:30 UTC, evgeniybalagurov requested changes
Павел, отлично поработал. Есть замечания которые необходимо исправить. Примерно накидал реализацию эффекта наведения на ссылки через псевдоэлементы.

2022-06-08 16:30 UTC, evgenybalagurov commented on index.html
> +      <ul class="header__navi_list">
Возможно имелся ввиду элемент header__navi-list. По БЭМ модификатор нельзя использовать отдельно от элемента на одном узле.

2022-06-08 16:30 UTC, evgenybalagurov commented on index.html
> +          <span class="header__elipse header__elipse_type_left"></span>
Нужно убрать все span и реализовать эффект наведения через псевдо элементы. Примерно так:

          .header__link:hover:before {
            content: '';
            background-image: url(../../../images/Ellipse-left.svg);
            background-repeat: no-repeat;
            width: 100%;
            height: 100%;
            display: block;
            position: absolute;
            top: 0;
            left: -10px;
          }

          .header__link:hover:after {
            content: '';
            background-image: url(../../../images/Ellipse-right.svg);
            background-repeat: no-repeat;
            width: 100%;
            height: 100%;
            display: block;
            position: absolute;
            top: 0;
            left: 100%;
          }

2022-06-08 16:30 UTC, evgenybalagurov commented on index.html
> +      <a class="header__to-support_link header__link" href="#">
Возможно имелся ввиду элемент header__to-support-link. По БЭМ модификатор нельзя использовать отдельно от элемента на одном узле.

2022-06-08 16:30 UTC, evgeniybalagurov commented on index.html
> +        <img class="header__to-support_plus" src="./images/header-plus.svg" alt="поддержать">
Возможно имелся ввиду элемент header__to-support-plus. По БЭМ модификатор нельзя использовать отдельно от элемента на одном узле.

2022-06-08 16:30 UTC, evgeniybalagurov commented on blocks/header/__navi/header__navi.css
> +}
Нужно добавить flex-grow: 1; что-бы элемент растягивался на всю ширину, т.к. блоку header назначено свойство justify-content: stretch;

2022-06-08 16:30 UTC, evgenybalagurov commented on blocks/header/__navi/_list/header__navi_list.css
> +  gap: 12.15px;
Вместо gap нужно задать justify-content: space-around; что-бы ссылки равномерно распределялись по всей ширине

2022-06-08 16:30 UTC, evgenybalagurov commented on blocks/header/__navi-link/header__navi-link.css
> +}
Нужно добавить position: relative; для корректной работы эффекта наведения на ссылки через псевдоэлементы

2022-06-08 16:30 UTC, evgenybalagurov commented on blocks/header/__social-links/header__social-links.css
> +  gap: 0.3px;
Нужно добавить flex-grow: 1; что-бы элемент растягивался на всю ширину, т.к. блоку header назначено свойство justify-content: stretch;

2022-06-08 16:30 UTC, evgeniybalagurov commented on index.html
> +    <div class="header__borders"></div>
Элемент нужно убрать, и реализовать горизонтальные линии через левый border header__social-links и header__to-support

2022-06-08 18:42 UTC, dimshaa requested changes
Отличный хедер! А станет только лучше. Тут до меня уже ребята поработали, так что мои замечания скорее эстетические.

2022-06-08 18:42 UTC, dimshaa commented on blocks/header/header.css
> +  border-bottom: 1px solid #242424;
Лучше использовать переменную. Но не криминально.

2022-06-08 18:42 UTC, dimshaa commented on blocks/header/__borders/header__borders.css
> +  bottom: 82.26%;
Не очень понял, зачем этот элемент. Мне кается, лучше его убрать и добавить border-left/border-right у соседних элементов. И еще при адаптиве его будет неудобно переопределять

UPD: Женя тоже про это написал, не заметил сразу

2022-06-08 18:42 UTC, dimshaa commented on index.html
> +        <img class="header__to-support_plus" src="./images/header-plus.svg" alt="поддержать">
Добавлю от себя, что это изображение неконтентное. Может, его лучше через background задать?

2022-06-08 18:42 UTC, dimshaa commented on blocks/header/__social-link/header__social-link.css
> +  text-transform: lowercase;
Не очень понял, для чего это свойство.

2022-06-08 19:09 UTC, Pavel-Rogozhkin commented on blocks/header/__social-link/header__social-link.css
> +  text-transform: lowercase;
Это для стилистики, если кто-то добавит свою соц-сеть и напишет её заглавными буквами, то всё равно будут строчными.

2022-06-09 18:19 UTC, Pavel-Rogozhkin commented on index.html
> +        <img class="header__to-support_plus" src="./images/header-plus.svg" alt="поддержать">
не получилось через фон, несколько раз пробовал по разному, пока оставил так...

2022-06-12 18:18 UTC, evgeniybalagurov approved these changes
Отлично получилось, нужно только line-height в десятичные значения поправить, убрать комментарии по коду, и пустой селектор header__link_active

2022-06-20 16:42 UTC, dimshaa approved these changes

2022-06-20 16:53 UTC, merged