Dmitriy mgn/#6
Pavel-Rogozhkin/Lubimovka pull request #20
Opened 2022-06-08 17:14 UTC by DmitriyMGN

Ребята, посмотрите пожалуйста мой кусок. 
Есть сомнения в элементе с анимацией, надо ли в css указывать keyframes или лучше сделать как-то отдельным блоком.

2022-06-08 19:05 UTC, Pavel-Rogozhkin requested changes

2022-06-08 19:05 UTC, Pavel-Rogozhkin commented on blocks/social/social.css
> +  background-color: #ECEBE8;
используй тут переменную var(--main-bg-color);

2022-06-08 19:05 UTC, Pavel-Rogozhkin commented on blocks/social/__head-image/social__head-image.css
> +  background-image: url(../../../images/social__head-image.png);
Добавить 
background-size: contain;
background-repeat: no-repeat;
и мб width вообще не нужен будет?

2022-06-08 19:05 UTC, Pavel-Rogozhkin commented on blocks/social/__link/social__link.css
> +@keyframes pulse {
с кнопками потом будем подумать как правильно по макету их сделать надо.

2022-06-08 19:57 UTC, nlog675 reviewed
Привет!
Отличная работа, практически нечего исправлять!

2022-06-08 19:57 UTC, nlog675 commented on index.html
> +            <a href="#" class="social__link">&rarr;fb</a>
добавь ссылкам атрибут target

2022-06-08 19:57 UTC, nlog675 commented on blocks/social/__links/social__links.css
> +  justify-content: center;
если отключить это свойство, то ничего не поменяется

2022-06-09 12:05 UTC, DmitriyMGN commented on blocks/social/__link/social__link.css
> +@keyframes pulse {
окей

2022-06-09 12:14 UTC, DmitriyMGN commented on blocks/social/__links/social__links.css
> +  justify-content: center;
поправил

2022-06-09 12:15 UTC, DmitriyMGN commented on index.html
> +            <a href="#" class="social__link">&rarr;fb</a>
поправил

2022-06-09 12:15 UTC, DmitriyMGN commented on blocks/social/__head-image/social__head-image.css
> +  background-image: url(../../../images/social__head-image.png);
поправил

2022-06-09 12:15 UTC, DmitriyMGN commented on blocks/social/social.css
> +  background-color: #ECEBE8;
окей

2022-06-09 12:19 UTC, DmitriyMGN commented on blocks/social/__link/social__link.css
> +@keyframes pulse {
пока оставлю тогда

2022-06-09 16:51 UTC, Pavel-Rogozhkin approved these changes

2022-06-09 20:14 UTC, evgeniybalagurov reviewed
Все классно, молодец Дима.
Есть несколько незначительных замечаний.

2022-06-09 20:14 UTC, evgenybalagurov commented on blocks/social/__head-image/social__head-image.css
> +  background-image: url(../../../images/social__head-image.png);
Теперь если вставить другое изображение меньшей ширины, оно уходит в левый край, предлагаю указать свойства background-size: cover; background-position: center;

2022-06-09 20:14 UTC, evgenybalagurov commented on blocks/social/__head-image/social__head-image.css
> +  background-image: url(../../../images/social__head-image.png);
Для изображений которые не содержат прозрачности предпочтительнее использовать формат JPEG.

2022-06-09 20:14 UTC, evgenybalagurov commented on index.html
> +            <a href="#" target="_blank" class="social__link">&rarr;fb</a>
В секции projects ниже header есть ссылка "проекты" она похожа эеркально на эти ссылки. Предлагаю вынести элемент social__link в отдельный блок link.

2022-06-09 20:14 UTC, evgenybalagurov commented on index.html
> +          <h2 class="social__title">Рассказать<br> о спектакле в соцсетях</h2>
Предлагаю вынести текст в отдельный блок - text-block и создавать для него элементы и модификаторы в зависимости от ситуации. В своей секции я использовал элемент text-block__title для заголовка, вместо элемента social__title тоже можно использовать text-block__title. И создать модификатор .text-block_placed_social для задания margin

2022-06-10 07:35 UTC, DmitriyMGN commented on blocks/social/__head-image/social__head-image.css
> +  background-image: url(../../../images/social__head-image.png);
сделано

2022-06-10 07:35 UTC, DmitriyMGN commented on blocks/social/__head-image/social__head-image.css
> +  background-image: url(../../../images/social__head-image.png);
сделано

2022-06-10 07:35 UTC, DmitriyMGN commented on index.html
> +            <a href="#" target="_blank" class="social__link">&rarr;fb</a>
сделано

2022-06-10 07:35 UTC, DmitriyMGN commented on index.html
> +          <h2 class="social__title">Рассказать<br> о спектакле в соцсетях</h2>
сделано

2022-06-12 16:11 UTC, merged