Develop
Pavel-Rogozhkin/Lubimovka pull request #8
Opened 2022-06-02 20:52 UTC by Pavel-Rogozhkin

merge into main... (так как сильно устал и всё забыл)

2022-06-02 22:00 UTC, evgeniybalagurov commented
Накидал примерно структуру и подключение шрифтов https://disk.yandex.ru/d/yxaI9CsLvWzjkA.

2022-06-02 22:06 UTC, evgeniybalagurov reviewed
Накидал примерно структуру и подключение шрифтов https://disk.yandex.ru/d/yxaI9CsLvWzjkA.

2022-06-03 07:33 UTC, dimshaa commented on index.html
> +</head>
Стили на этом этапе лучше подключить здесь. Иначе сложно будет дебажить.

2022-06-03 07:33 UTC, dimshaa commented on pages/index.js
> +import './index.css';
Это же подключение для сборки вебпаком. Стили лучше подключать в head в index.html

2022-06-03 07:35 UTC, dimshaa requested changes
Я не очень понял зачем поменяли структуру. Изначально было правильное подключение стилей и общая структура проекта.

2022-06-03 07:56 UTC, evgeniybalagurov commented
Ну да, стили нужно в head подключить.

2022-06-03 08:25 UTC, evgeniybalagurov approved these changes

2022-06-03 08:31 UTC, dimshaa approved these changes

2022-06-03 08:32 UTC, merged