Evgeniybalagurov/#5
Pavel-Rogozhkin/Lubimovka pull request #9
Opened 2022-06-04 19:19 UTC by evgeniybalagurov

Ребят проведите пожалуйста ревью. 
Выделил текст в отдельный блок, чтобы можно было его переиспользовать в других секциях добавляя свои элементы и модификаторы. Создал переменные для цвета текста, bg, border и поместил в page, в дальнейшем чтобы сделать темную тему.

2022-06-04 20:20 UTC, Pavel-Rogozhkin commented on pages/index.css
> +@import url(../blocks/feedback/feedback.css);
насколько я помню, сначала нужно импортировать стили всей секции, затем её элементов порядке прорисовки на странице.

2022-06-04 20:32 UTC, Pavel-Rogozhkin requested changes
добавить общий фон на всю страницу

2022-06-04 20:32 UTC, Pavel-Rogozhkin commented on blocks/page/page.css
> +  --main-bg-color: #e5e5e5;
add line:
background: #e5e5e5;

2022-06-05 05:36 UTC, evgeniybalagurov commented on pages/index.css
> +@import url(../blocks/feedback/feedback.css);
В данном случае блоки text-block, slider-navigation, switcher, slider-btn, slider, slide не являются элементами блока feedback и могут переиспользоваться в других вышестоящих секциях. По этому, расположение в данном случае не принципиально. Я думуаю, что они должны подключаться до отрисовки основных секций.)

2022-06-05 07:30 UTC, Pavel-Rogozhkin approved these changes

2022-06-05 10:42 UTC, dimshaa reviewed
Очень круто! Ты еще и пиксель перфект все сделал сразу. Еще может немного анимацию помягче сделать?

2022-06-05 10:42 UTC, dimshaa commented on blocks/slider-navigation/slider-navigation.css
> +  flex-direction: row;
в принципе, если ставим значение по умолчанию -- свойство можно не задавать. это не ошибка, но наш наставник говорит, что лучше не задавать явно значения по умолчанию.

2022-06-05 10:42 UTC, dimshaa commented on blocks/slide/slide.css
> +  background-color: #fff;
может, тоже в переменные вынесем?

2022-06-05 12:05 UTC, Pavel-Rogozhkin commented on blocks/slide/slide.css
> +  background-color: #fff;
можно

2022-06-05 16:09 UTC, DmitriyMGN requested changes
Очень круто и грамотно сделал свою секцию, код очень чистый и последовательный. Значения и свойства стилей выстроены упорядочено, хороший БЭМ, даже немного завидую! Есть небольшие комментария по коду.
Женя, молодец!

2022-06-05 16:09 UTC, DmitriyMGN commented on index.html
> +      <div class="text-block text-block_placed_center slider-navigation">
Может сделать slider-navigation отдельным узлом? А то получилось что на одном узле висит два блока, не уверен что это по БЭМ.

2022-06-05 16:09 UTC, DmitriyMGN commented on pages/index.css
> +@import url(../blocks/feedback/feedback.css);
Согласен с Женей, тут момент не принципиальный

2022-06-05 16:09 UTC, DmitriyMGN commented on blocks/slider-navigation/slider-navigation.css
> +  flex-direction: row;
Поддерживаю, строка` flex-direction: row;` лишняя, только если она у тебя не переопределяет ` flex-direction: column`

2022-06-05 16:53 UTC, evgeniybalagurov commented on blocks/slider-navigation/slider-navigation.css
> +  flex-direction: row;
Да, у меня тоже возникли сомнения можно ли так делать микс. Вынес slider-navigation в отдельный узел.

2022-06-05 16:54 UTC, evgeniybalagurov commented on index.html
> +      <div class="text-block text-block_placed_center slider-navigation">
Да, у меня тоже возникли сомнения можно ли так делать микс. Вынес slider-navigation в отдельный узел.

2022-06-08 06:14 UTC, DmitriyMGN approved these changes
Классная работа, чистый код!

2022-06-08 15:32 UTC, merged